### ISSUE TITLE
Definir ferramentas 

### ISSUE THREAD

**Issue by milenaaires** [Interacao-Humano-Computador/2022.2-Camara#4]
Descrição: Definir quais ferramentas serão utilizadas no projeto para comunicação, confecção de documentos, reuniões, etc.

Critérios de aceitação: Tabela com a ferramenta e o objetivo de seu uso.

Tarefas:

- [x] Escolher ferramenta 
- [x] Objetivo da ferramenta 
- [x] Justificar a escolha

**Comment by roddas** [comment]
Adicionei as seguintes ferramentas:

1. GitHub
2. Notion
3. Discord
4. Google Drive
5. MS PowerPoint
